"""empty message

Revision ID: 31e1d9758bdf
Revises: 183ae3d46c70
Create Date: 2017-05-11 10:41:49.822305

"""

# revision identifiers, used by Alembic.
revision = '31e1d9758bdf'
down_revision = '183ae3d46c70'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('start_amount', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'start_amount')
    ### end Alembic commands ###
