"""empty message

Revision ID: 3b618c5d9f8e
Revises: e0feeead509
Create Date: 2017-05-11 10:54:56.873378

"""

# revision identifiers, used by Alembic.
revision = '3b618c5d9f8e'
down_revision = 'e0feeead509'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
